### ISSUE TITLE
Requested Jobs and User detail pages are butt-ugly

### ISSUE THREAD

**Issue by Evidlo** [purdue-epics-ims/boilerconnect#11]
Please make them not suck.

**Comment by commedeschatons** [comment]
Org profile page should look pretty OK now. Not sure about job requests, since we should hide it unless the user is logged in. maybe we can discuss it tomorrow. 

I Placed the tags/categories at the top. merged it back onto develop. What do you think?

![screen shot 2015-03-09 at 1 04 03 am](https://cloud.githubusercontent.com/assets/8601268/6550178/32127268-c5f8-11e4-9f92-492bebad8127.png)

**Comment by Evidlo** [comment]
user_detail still needs to be updated
